In [1]:
# NumPy的ndarray：一种多维数组对象
import numpy as np

In [2]:
data = np.array([[ 0.9526, -0.246 , -0.8856],
                 [ 0.5639,  0.2379,  0.9104]])
data

array([[ 0.9526, -0.246 , -0.8856],
       [ 0.5639,  0.2379,  0.9104]])

In [3]:
data * 10

array([[ 9.526, -2.46 , -8.856],
       [ 5.639,  2.379,  9.104]])

In [4]:
data + data

array([[ 1.9052, -0.492 , -1.7712],
       [ 1.1278,  0.4758,  1.8208]])

In [5]:
data.shape

(2, 3)

In [6]:
# 创建ndarray

In [7]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [8]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
arr2.ndim # 维度

2

In [10]:
arr2.shape # 形状

(2, 4)

In [11]:
arr1.dtype # 数据类型

dtype('float64')

In [12]:
arr2.dtype

dtype('int32')

In [13]:
np.zeros(10) # 快速初始化一个数组

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [14]:
np.empty((2, 3, 2)) # 与zeros不同，empty给的是随机数

array([[[  1.43365469e-311,   2.81617418e-322],
        [  0.00000000e+000,   0.00000000e+000],
        [  4.03723418e-270,   1.16095484e-028]],

       [[  4.62356592e+252,  -3.52847249e-203],
        [ -1.14920591e+182,   6.32672818e+180],
        [  4.74483502e+170,   9.75018641e-072]]])

In [15]:
np.arange(15) # 生成一个有序序列

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
# 数组创建函数
# array：           将输入数据（列表、元组、数组或其他序列类型）转换为ndarray。
#                   要么推断出dtype，要么显示指定dtype。默认直接复制输入数据。
# asarray：         将输入转换为ndarray，如果输入本身就是一个ndarray就不进行复制。
# arange：          类似于内置的range。但返回的是一个ndarray而不是列表。
# ones/ones_like：  根据指定的形状和dtype创建一个全1数组。
#                   ones_like以另一个数组为参数，并根据其形状和dtype创建一个全1数组。
# zeros/zeros_like：类似于ones和ones_like，只不过产生的是全0数组而已。
# empty/empty_like；创建新数组，只分配内存空间但不填充任何值。
# eye/identuty：    创建一个正方的NxN单位矩阵（对角线为1，其余为0）

In [17]:
# ndarray的数据类型

In [18]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [19]:
arr = np.array([1, 2, 3, 4, 5])
float_arr = arr.astype(np.float64) # 类型转换
float_arr.dtype

dtype('float64')

In [20]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [21]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float) # 字符串转浮点数，如果有元素失败会触发TypeError。

array([  1.25,  -9.6 ,  42.  ])

In [22]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype) # 利用其他array的类型做转换

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [23]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32 # 因为是empty，所以随机整数。

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

In [24]:
# 数组和标量之间的运算

In [25]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr * arr) # 对应位置元素相乘
print(arr - arr) # 对应位置元素相减

[[  1.   4.   9.]
 [ 16.  25.  36.]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [26]:
1 / arr # 除法作用在每个元素上

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [27]:
arr ** 0.5 # 每个元素开根号

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

In [28]:
# 基本的索引和切片

In [29]:
arr = np.arange(10)
arr[5:8] # 开区间

array([5, 6, 7])

In [30]:
arr[5:8] = 12 # 与list不同，这里切片是引用，赋值的话每个元素都更新。
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [31]:
arr_slice = arr[5:8]
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [32]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [33]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [34]:
arr2d[0][2] # arr2d[0, 2]等价，先行后列。

3

In [35]:
arr3d = np.array([[[1, 2, 3],
                   [4, 5, 6]],
                  [[7, 8, 9],
                   [10, 11, 12]]]) # 3维数组
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [36]:
old_values = arr3d[0].copy()
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [38]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [39]:
arr3d[1, 0, 2] # x-y-z

9

In [40]:
# 切片索引

In [41]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [42]:
arr2d[:2] # 前2行

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
arr2d[:2, 1:] # 前2行，和除第0列构成的二维数组

array([[2, 3],
       [5, 6]])

In [44]:
print(arr2d[1, :2])
print(arr2d[2, :1])

[4 5]
[7]


In [45]:
arr2d[:, :1] # :代表选取整个轴

array([[1],
       [4],
       [7]])

In [46]:
arr2d[:2, 1:] = 0 # 赋值操作作用于每个元素
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [47]:
# 布尔型索引

In [48]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(names)
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[-0.23006926  1.15881221 -1.18604836  0.6048498 ]
 [-1.21231307  1.06774606  0.36241613  1.57925242]
 [ 0.20719471 -1.066013   -0.38300115 -1.79161271]
 [ 1.71836503  1.73377944  1.37166248  2.20440881]
 [ 0.88666314 -0.30883462 -1.36278318  0.50081156]
 [-0.50091826  0.62506898 -0.79846889  0.45160213]
 [-0.75410773 -0.9422558   0.93424908 -1.10212424]]


In [49]:
names == 'Bob' # 返回布尔数组

array([ True, False, False,  True, False, False, False], dtype=bool)

In [50]:
data[names == 'Bob'] # 布尔数组的值匹配每一行，True则选取，False则扔掉。

array([[-0.23006926,  1.15881221, -1.18604836,  0.6048498 ],
       [ 1.71836503,  1.73377944,  1.37166248,  2.20440881]])

In [51]:
data[names == 'Bob', 2:] # 去除前2列

array([[-1.18604836,  0.6048498 ],
       [ 1.37166248,  2.20440881]])

In [52]:
data[names == 'Bob', 3] # 保留第3列

array([ 0.6048498 ,  2.20440881])

In [53]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True], dtype=bool)

In [54]:
data[~(names == 'Bob')] # 书里用-，现在不支持，必须用~表示逻辑取反。

array([[-1.21231307,  1.06774606,  0.36241613,  1.57925242],
       [ 0.20719471, -1.066013  , -0.38300115, -1.79161271],
       [ 0.88666314, -0.30883462, -1.36278318,  0.50081156],
       [-0.50091826,  0.62506898, -0.79846889,  0.45160213],
       [-0.75410773, -0.9422558 ,  0.93424908, -1.10212424]])

In [55]:
mask = (names == 'Bob') | (names == 'Will') # 条件混合，取或
data[mask]

array([[-0.23006926,  1.15881221, -1.18604836,  0.6048498 ],
       [ 0.20719471, -1.066013  , -0.38300115, -1.79161271],
       [ 1.71836503,  1.73377944,  1.37166248,  2.20440881],
       [ 0.88666314, -0.30883462, -1.36278318,  0.50081156]])

In [56]:
data[data < 0] = 0 # 小于0的值置为0
data

array([[ 0.        ,  1.15881221,  0.        ,  0.6048498 ],
       [ 0.        ,  1.06774606,  0.36241613,  1.57925242],
       [ 0.20719471,  0.        ,  0.        ,  0.        ],
       [ 1.71836503,  1.73377944,  1.37166248,  2.20440881],
       [ 0.88666314,  0.        ,  0.        ,  0.50081156],
       [ 0.        ,  0.62506898,  0.        ,  0.45160213],
       [ 0.        ,  0.        ,  0.93424908,  0.        ]])

In [57]:
data[names != 'Joe'] = 7
data

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.        ,  1.06774606,  0.36241613,  1.57925242],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.        ,  0.62506898,  0.        ,  0.45160213],
       [ 0.        ,  0.        ,  0.93424908,  0.        ]])

In [58]:
# 花式索引

In [59]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [60]:
arr[[4, 3, 0, 6]] # 选择指定的行

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [61]:
 arr[[-3, -5, -7]] # 负数索引依然可用

array([[ 5.,  5.,  5.,  5.],
       [ 3.,  3.,  3.,  3.],
       [ 1.,  1.,  1.,  1.]])

In [62]:
arr = np.arange(32).reshape((8, 4)) # 重新调整数组形状
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [63]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]] # 实际选取的是[1, 0]，[5， 3]，[7， 1]，[2， 2]。

array([ 4, 23, 29, 10])

In [64]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]] # 这样才是选一个子数组的正确形式

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [65]:
arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])] # np.ix_函数可以将两个一维整数数组转换为一个用于选取方形区域的索引器

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [66]:
# ！！！ 花式索引跟切片不一样，它总是将数据复制到新数组中。

In [67]:
# 数组转置和轴对换

In [68]:
arr = np.arange(15).reshape((3, 5))
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [69]:
arr = np.random.randn(6, 3)
np.dot(arr.T, arr) # 矩阵乘法，3行6列 * 6行3列 = 3行3列

array([[ 5.21173201, -1.87420577, -1.42573842],
       [-1.87420577,  8.23902472, -0.01110902],
       [-1.42573842, -0.01110902,  4.07792519]])

In [70]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [71]:
arr.transpose((1, 0, 2)) # new[y, x, z] = old[x, y, z]

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [72]:
arr.swapaxes(1, 2) # 轴交换

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])