In [1]:
# 通用函数：快速的元素级数组函数
import numpy as np

In [2]:
arr = np.arange(10)
np.sqrt(arr) # ufunc，作用在每个元素上

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [3]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [4]:
x = np.random.randn(8)
y = np.random.randn(8)
np.maximum(x, y) # 二元函数，接受2个数组作为参数，并按对应位置进行操作。

array([ 0.66825501, -0.23642231,  0.43557658,  1.67213174,  0.42920574,
        1.88044069,  1.21284547,  1.18446622])

In [5]:
arr = np.random.randn(7) * 5
print(arr)
np.modf(arr) # 分别打印小数与整数部分

[ 11.20515537  -1.96737775  -0.63960607  -1.15697875   0.05848623
  -0.29945217  -1.37434553]


(array([ 0.20515537, -0.96737775, -0.63960607, -0.15697875,  0.05848623,
        -0.29945217, -0.37434553]),
 array([ 11.,  -1.,  -0.,  -1.,   0.,  -0.,  -1.]))

In [6]:
# 一元ufunc
# abs/fabs
# sqrt
# square
# exp
# log/log10/log2/log1p：log1p = log(1 + x)
# sign
# ceil：                向上取整
# floor：               向下取整
# rint：                四舍五入
# modf：                将数组的小数和整数部分以两个独立数组的形式返回
# isnan
# isfinite/isinf
# cos/cosh
# sin/sinh
# tan/tanh
# arrcos/arccosh
# arrsin/arcsinh
# arrtan/arctanh
# logical_not：         计算各元素not x的真值，相当于~arr。

In [7]:
# 二元ufunc
# add
# subtract
# multiply
# divide/floor_divide
# power
# maximum/fmax
# minimum/fmin
# mod
# copysign
# greater/greater_equal
# less/less_equal
# equal/not_equal
# logic_and/or/xor