In [1]:
# 线性代数
import numpy as np
from numpy.linalg import inv, qr

In [2]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x.dot(y) # 矩阵乘法

array([[  28.,   64.],
       [  67.,  181.]])

In [3]:
np.dot(x, np.ones(3)) # 2*3矩阵乘以一个3*1矩阵

array([  6.,  15.])

In [4]:
x = np.random.randn(5, 5)
mat = x.T.dot(x)
mat_i = inv(mat)
print(mat_i)
print(mat.dot(mat_i)) # 单位矩阵，因为浮点数，所以非对角线元素为非0的非常小的数。

[[ 0.99946364  0.42488643 -0.53900775 -0.9701616   0.45676171]
 [ 0.42488643  0.45529242 -0.32430143 -0.6244948   0.26716755]
 [-0.53900775 -0.32430143  2.6797144   0.56083036 -2.4860754 ]
 [-0.9701616  -0.6244948   0.56083036  1.57454682 -0.45628419]
 [ 0.45676171  0.26716755 -2.4860754  -0.45628419  2.58170138]]
[[  1.00000000e+00  -4.37715753e-17   2.29547615e-16  -8.81655164e-17
    1.73487789e-17]
 [ -2.63382816e-16   1.00000000e+00   2.91494870e-16  -4.23624252e-17
   -1.13579522e-16]
 [  2.61904855e-17   8.32944592e-17   1.00000000e+00  -2.43846592e-16
    1.58904870e-15]
 [ -9.69321863e-17  -1.13633466e-17   4.75161964e-16   1.00000000e+00
   -6.22206142e-17]
 [ -2.36280139e-18   5.65816389e-17  -3.07226737e-16   1.08127679e-16
    1.00000000e+00]]


In [5]:
q, r = qr(mat) # qr分解
q

array([[-0.87346405,  0.03568355,  0.03011668,  0.4682239 ,  0.12508642],
       [ 0.13746522, -0.93839611,  0.04066364,  0.30579304,  0.07316513],
       [-0.07502753, -0.06490287, -0.71969369,  0.09315781, -0.68082384],
       [-0.46082062, -0.33609472,  0.09215151, -0.8065847 , -0.12495564],
       [-0.01338287, -0.03110275, -0.68628605, -0.16733122,  0.70701148]])

In [6]:
# 常用线性代数函数
# diag： 以一维数组形式返回方阵的对角线（或非对角线）元素，
#        或将一维数组转换为方阵。
# dot：  矩阵乘法
# trace：计算对角线元素的和
# det：  计算矩阵行列式
# eig：  计算方阵的本征值和本征向量
# inv：  计算方阵的逆
# pinv： 就按矩阵的Moore-Penrose伪逆
# qr：   计算QR分解
# svd：  计算奇异值分解（SVD）
# solve：解线性方程组Ax = b，其中A为一个方阵。
# lstsq：计算Ax = b的最小二乘解