In [1]:
# 多元线性回归
import matplotlib.pyplot as plt
import numpy as np
from numpy.linalg import inv
from sklearn.linear_model import LinearRegression

%matplotlib inline

In [2]:
# 场景如下
# y = a * x1 + b * x2 + c
#                   | a |
# y = [x1, x2, 1] * | b |
#                   | c |

In [3]:
# 简单讲下多元线性回归问题，就是对方程Y=Xβ求解β。
# 如果是方阵的话就很简单：β = X逆 * Y。
# 但是事实没这么简单，我们有另一个方法，可以用X.T * X把X变成方阵。
# X的维度a * b，β的维度b * 1
# Y的维度a * 1
# X.T * X = X'后得到一个b * b的方阵。
# X.T * Y后得到Y'，一个b * 1的矩阵。
# Y' = X'β
# X'逆 * Y' = β

In [4]:
x = [[1,1,1],[1,1,2],[1,2,1]]
y = [[6],[9],[8]]
xt = np.transpose(x) # 转置
xs = np.dot(xt, x) # 矩阵乘法
ys = np.dot(xt, y)
# inv求逆矩阵
np.dot(inv(xs), ys) # y = 1 + 2 * x1 + 3 * x2

array([[ 1.],
       [ 2.],
       [ 3.]])

In [5]:
model = LinearRegression()
model.fit(x, y)
print(model.coef_)
print(model.intercept_) # 变成y = ax1 + bx2 + cx3 + d形式

[[ 0.  2.  3.]]
[ 1.]


In [6]:
x2 = [[1,3,5]]
model.predict(x2)

array([[ 22.]])