In [1]:
# 特征提取
import numpy as np
from sklearn import preprocessing
from sklearn.feature_extraction import DictVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
onehot_encoder = DictVectorizer()
instances = [{'city': '北京'},{'city': '天津'}, {'city': '上海'}]
onehot_encoder.fit_transform(instances).toarray()

array([[ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.]])

In [3]:
corpus = ['UNC played Duke in basketball',
          'Duke lost the basketball game' ]
vectorizer = CountVectorizer()
print(vectorizer.fit_transform(corpus).todense())
print(vectorizer.vocabulary_) # 单词对应数组的位置

[[1 1 0 1 0 1 0 1]
 [1 1 1 0 1 0 1 0]]
{'unc': 7, 'played': 5, 'duke': 1, 'in': 3, 'basketball': 0, 'lost': 4, 'the': 6, 'game': 2}


In [4]:
corpus = ['The dog ate a sandwich and I ate a sandwich',
          'The wizard transfigured a sandwich' ]
vectorizer = TfidfVectorizer(stop_words='english')
print(vectorizer.fit_transform(corpus).todense()) # 带权重信息
print(vectorizer.vocabulary_)

[[ 0.75458397  0.37729199  0.53689271  0.          0.        ]
 [ 0.          0.          0.44943642  0.6316672   0.6316672 ]]
{'dog': 1, 'ate': 0, 'sandwich': 2, 'wizard': 4, 'transfigured': 3}


In [5]:
x = np.array([[0, 0, 5, 13, 9, 1],
              [0, 0, 13, 15, 10, 15],
              [0, 3, 15, 2, 0, 11]],
             dtype='float64')
x_scaled = preprocessing.scale(x) # scale是对每一列数据进行的
x_scaled

array([[ 0.        , -0.70710678, -1.38873015,  0.52489066,  0.59299945,
        -1.35873244],
       [ 0.        , -0.70710678,  0.46291005,  0.87481777,  0.81537425,
         1.01904933],
       [ 0.        ,  1.41421356,  0.9258201 , -1.39970842, -1.4083737 ,
         0.33968311]])

In [6]:
x_scaled.mean(axis=0)

array([  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   3.70074342e-17])

In [7]:
x_scaled.std(axis=0)

array([ 0.,  1.,  1.,  1.,  1.,  1.])